### ISSUE TITLE
Application crashes after the onPause method

### ISSUE THREAD

**Issue by karambar** [Instabug/android-sample#2] opened 2016-02-12 19:14 UTC
On some devices (Samsung galaxy S4 for example), when I close the app from a screen have a map, your SDK crashes with the following stack trace:

`        java.lang.RuntimeException: Unable to stop activity {fr.chauffeurprive.preprod.debug/fr.chauffeurprive.presentation.order.view.OrderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.internal.storage.cache.d.b()' on a null object reference
                                                                                     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4154)
                                                                                     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4217)
                                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:177)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.internal.storage.cache.d.b()' on a null object reference
                                                                                     at com.instabug.library.internal.storage.cache.o.c(ReadQueueCacheManager.java:60)
                                                                                     at com.instabug.library.ak.b(SessionManager.java:59)
                                                                                     at com.instabug.library.o.d(InstabugDelegate.java:283)
                                                                                     at com.instabug.library.Instabug.notifyDelegateActivityStopped(Instabug.java:142)
                                                                                     at com.instabug.library.h.onActivityStopped(InstabugActivityLifecycleListener.java:41)
                                                                                     at android.app.Application.dispatchActivityStopped(Application.java:250)
                                                                                     at android.app.Activity.onStop(Activity.java:1662)
                                                                                     at android.support.v4.app.FragmentActivity.onStop(FragmentActivity.java:562)
                                                                                     at fr.chauffeurprive.presentation.order.view.OrderActivity.onStop(OrderActivity.java:414)
                                                                                     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1275)
                                                                                     at android.app.Activity.performStop(Activity.java:6493)
                                                                                     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4149)
                                                                                     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4217) 
                                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:177) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:145) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
`

**Comment by mSobhy90** [comment] 2016-02-14 14:17
Hey @karambar, thanks for reporting this.
We're currently looking into it, can you please provide me with more details (if any). Like, is it something consistent, is the maps activity the last activity in your stack or are you using the home button and removing it from recents, etc...

**Comment by karambar** [comment] 2016-02-15 09:56
Hi @mSobhy90 , thanks for your answer.

I did some tests and I have found which use of the SDK was generating this bug. I initialise the Instabug SDK from my custom Application class and I immediately disable it using the method Instabug.disable().
Indeed, I want to make this feature only available for some clients so I disable it by default and only enable it according to a list of beta testers. However, call the method Instabug.disable() just after the SDK initialisation cause a crash when I leave the app. If I don't disable the SDK, everything is fine and the app is not crashing anymore.

Do you have a tips for me to only enable Instabug for some clients ? I could build the SDK after the login process but I find this usage dangerous.

Otherwise, to answer your questions, this crash is consistent and appears on every devices I have. Moreover, I'm not using the home button, I press the back button which makes me leave the app because the maps activity is the last activity in my stack.

**Comment by mSobhy90** [comment] 2016-02-15 14:00
Hi @karambar, thanks for the detailed report.

As for the use-case you mentioned, let me check it out and I'll get back to you about it.

As for enabling Instabug to certain users, we had that case in mind when designing the builder.
You can build Instabug in the Application class as normal with 1 difference, the `build()` function has an overload which takes state `build(Feature.State instabugInitialState)`. So in that scenario you'll have something following this pattern.

```
public class App extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        new Instabug.Builder(this, "<TOKEN>")
                .build(Feature.State.DISABLED);
    }
}
```
And then when user clicks some button in the settings screen (or wherever):
```
        if (Instabug.isEnabled()) {
            Instabug.disable();
        } else {
            Instabug.enable();
        }
```
That should achieve your scenario. Can you please confirm?

**Comment by karambar** [comment] 2016-02-16 09:42
Thanks @mSobhy90 for your detailed answer !

We integrated your modifications and the behaviours is much more better, however we noticed a new issue in a very specific use-case.
You can reproduce this bug following these steps:

- Build Instabug with `build(Feature.State.DISABLED)`
- Enable it on activity button click (log in button in our app)
- Disable it programmatically when the user click on a button (logout button for us)
- Kill the app
- Relaunch the app (It will build Instabug as in the first step)
- Enable Instabug on activity button click (same as the second step)
- Close the app
- Kaboom !

And it generates the following stack trace : 

`INSTABUG - Instabug: Instabug Caught an Unhandled Exception: java.lang.RuntimeException
                                                        java.lang.RuntimeException: Unable to stop activity {fr.chauffeurprive.preprod/fr.chauffeurprive.presentation.order.view.OrderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.internal.e.a.d.b()' on a null object reference
                                                            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3500)
                                                            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
                                                            at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:148)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.instabug.library.internal.e.a.d.b()' on a null object reference
                                                            at com.instabug.library.internal.e.a.o.c(ReadQueueCacheManager.java:60)
                                                            at com.instabug.library.k.b(SessionManager.java:59)
                                                            at com.instabug.library.ab.d(InstabugDelegate.java:283)
                                                            at com.instabug.library.Instabug.notifyDelegateActivityStopped(Instabug.java:142)
                                                            at com.instabug.library.v.onActivityStopped(InstabugActivityLifecycleListener.java:41)
                                                            at android.app.Application.dispatchActivityStopped(Application.java:232)
                                                            at android.app.Activity.onStop(Activity.java:1620)
                                                            at android.support.v4.app.FragmentActivity.onStop(FragmentActivity.java:562)
                                                            at fr.chauffeurprive.presentation.order.view.OrderActivity.onStop(OrderActivity.java:415)
                                                            at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1278)
                                                            at android.app.Activity.performStop(Activity.java:6395)
                                                            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3497)
                                                            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550) 
                                                            at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                            at android.os.Looper.loop(Looper.java:148) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

The crash seems to be the same, please let me know if you need more details or if you want me to do a new issue for this bug.

**Comment by mSobhy90** [comment] 2016-02-18 11:09
Hi @karambar, sorry for my late response, and thanks again for your detailed reports it's deeply appreciated.
I've been able to reproduce the issue, and I've worked out a fix for both cases. It'll be rolling out by end of today.
Thanks a lot @karambar for helping us make Instabug better. :beers:

**Comment by mSobhy90** [comment] 2016-02-18 17:06
Closing this since v2.2 was released containing this fix

**Closed by mSobhy90** 2016-02-18 17:06 UTC
Labels: bug

**Comment by karambar** [comment] 2016-02-19 13:02
Thank you very much @mSobhy90 for your reactivity !
We integrated your new release and everything seems to be OK . :rocket:
