### ISSUE TITLE
Screenshot gesture invocation event does not work on some devices

### ISSUE THREAD

**Issue by joharei** [Instabug/android-sample#33] opened 2017-05-09 10:33 UTC
The screenshot gesture invocation event doesn't seem to work on Samsung Galaxy S8, with Android 7.0.

Instabug is set up like this:
```java
new Instabug.Builder(application, "token")
    .setInvocationEvent(InstabugInvocationEvent.SCREENSHOT_GESTURE)
    .build();
```
This works on all other devices I've tested with.

**Comment by tarek360** [comment] 2017-05-09 11:58
Hi @joharei Thank you for reporting this, we will check it and feedback you, thanks.

**Comment by tarek360** [comment] 2017-05-10 11:47
Hi @joharei Could you provide me with the default path of the screenshots directory on your Samsung Galaxy S8, please?

**Comment by joharei** [comment] 2017-05-11 08:23
Hi,
It's in internal storage under DCIM/Screenshots.

After more testing, I have found that it also doesn't work on Google Pixel (screenshots in Pictures/Screenshots), or on Samsung Galaxy A5 (2016, screenshots in DCIM/Screenshots).

On Samsung Galaxy S4 (screenshots in Pictures/Screenshots), this is working on my debug build, but not in my release build (using ProGuard).

**Comment by tarek360** [comment] 2017-05-11 12:47
@joharei , what's​ the SDK version which you use?

**Comment by joharei** [comment] 2017-05-11 14:50
I use the 4.0.10 version of Instabug

If you meant Android SDK version, my `targetSdkVersion` is 25, and my `minSdkVersion` is 16.

**Comment by joharei** [comment] 2017-05-15 11:24
Is there any news on this? We changed from using the shake invocation because the sensitivity was hard to get reliable without being irritating. Many users are now unable to send us feedback.

Thanks in advance :)

**Comment by reemalashry1** [comment] 2017-05-21 11:33
Hello @joharei This is Reem from Instabug, I've sent you an email to follow up on this issue, please check it :)

**Comment by joharei** [comment] 2017-05-21 16:20
Hi @reemalashry1! I can't find find any email from you. Can you send it again please?

**Comment by tarek360** [comment] 2017-06-04 00:30
Thank you @joharei for reporting this, as you know the issue is fixed and will be released in the next version.

**Closed by tarek360** 2017-06-04 00:30 UTC

**Comment by qandeelabbassi** [comment] 2019-05-21 22:34
@tarek360 tested on Huawei Mate 10 (lite). Screenshot gesture not working with latest sdk as of now.
